version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      MONGO_URL: "mongodb://pivasia:fjeu3duqe7j6JEMcr@10.101.3.215:27017/PIVASIA"
      ROOT_URL: "https://vldc.fimo.edu.vn"
      METEOR_SETTINGS: '{
        "public": {
        },
        "private": {
          "smtp": {
            "server": "smtp.gmail.com",
            "username": "",
            "password": "",
            "port": 587
          },
          "odbc": {
            "postgreSQL": {
              "user": "",
              "password": "",
              "host": "",
              "port": "",
              "database": ""
            }
          }
        },
        "env": {}
      }'
